<?php
return [
    'email_footer' => 'यस इ-मेल ठेगानामा कुनै पनि इमेललाई जवाफ नदिनुहोस्। यो इमेल हाम्रो प्रणाली द्वारा स्वचालित रूपमा पठाएको छ। ',
    'login_message' => 'कृपया तपाइँको सत्र सुरु गर्न लग इन गर्नुहोस्',
    'text_forgot_password' => 'पासवर्ड बिर्सनुभयो?',
    'page_title_login' => 'लगइन प्यानल',
    'page_title_forgot' => 'पासवर्ड बिर्सनुभयो',
    'forgot_message' => 'पासवर्ड अनुरोध गर्न तपाईको ईमेल ठेगाना प्रविष्टि गर्नुहोस्',
    "forgot_text_try_again" => "पुनः लगइन प्रयास गर्नुहोस् ?",
    'text_no_notification' => "तपाईंसँग 0 सूचनाहरू छन्",
    'text_view_all_notification' => 'सबै हेर्नुहोस्',
    'label_button_profile' => "प्रोफाइल",
    'filter_dialog_title' => 'उन्नत क्रमबद्ध र फिल्टर',
    'there_is_no_option' => 'यस इनपुटप्रकारको लागि कुनै विकल्प सेटिङ छैन',
    'no' => 'नहीं।',

    'text_enter_the_password' => 'तपाइँको सत्र पुन: प्राप्त गर्न आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्',
    'text_or_sign_in' => 'वा फरक प्रयोगकर्ताको रूपमा साइन इन गर्नुहोस्',
    'text_default_add_new_module' => 'नयाँ थप्नुहोस्: मोड्युल',
    'text_default_list_module' => 'सूची: मोड्युल',
    'text_default_help_password' => 'न्यूनतम 5 क्यारेक्टरहरू। कृपया खाली छोड्नुहोस् भने तपाईंले पासवर्ड परिवर्तन गर्नुभएन.',
    'text_default_help_upload' => 'फाइल प्रकार समर्थन: JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'तपाई केवल संख्या मात्र प्रविष्ट गर्न सक्नुहुन्छ',
    'text_default_help_email' => 'कृपया मान्य ईमेल ठेगाना प्रविष्ट गर्नुहोस्',
    'text_default_help_text' => 'तपाईं मात्र अक्षर मात्र प्रविष्ट गर्न सक्नुहुन्छ',
    'text_default_help_url' => 'एक वैध URL प्रविष्ट गर्नुहोस्',
    'text_dashboard' => 'ड्याशबोर्ड',
    'text_delete' => 'मेटाउन',
    'text_prefix_option' => '** एउटा चयन गर्नुहोस्',
    'text_loading' => 'कृपया लोड पर्खनुहोस् ...',

    'message_after_logout' => 'धन्यवाद, तपाई पछि हेर्नुहोस्!',
    'message_forgot_password' => 'हामीले तपाईंको इमेलमा नयाँ पासवर्ड पठाएका छौं, इनबक्स जाँच गर्नुहोस् वा स्पामबक्स!',

    'page_not_found' => 'ओहो! पृष्ठ फेला परेन',
    'page_not_found_text' => 'हामी खोज्न असमर्थ छौं पृष्ठ खोज्नु भएको छ।',
    'page_not_found_tips' => '* कृपया निश्चित गर्नुहोस् URL URL सही छ<br/>
                * कृपया निश्चित गर्नुहोस् कि फन्ट क्यापिटलिङ सही छ किनकि केस संवेदनशील<br/>
                * सायद तपाईंले खोज्नु भएको पृष्ठ प्रशासकद्वारा मेटाईयो<br/>
                * तपाईं ब्राउजरमा ब्याक बटन क्लिक गरेर फिर्ता जान सक्नुहुन्छ<br/>',

    'log_try_view' => 'डाटा हेर्नुहोस्: मोडलमा नाम:',
    'log_try_edit' => 'डाटा सम्पादन गर्ने प्रयास गर्नुहोस्: मा नाम: मोड्युल',
    'log_try_add' => 'डेटा थप गर्नुहोस् प्रयास गर्नुहोस्: मोड्युल',
    'log_try_add_save' => 'डाटा थप गर्नुहोस्: नाम डेटा मा: मोड्युल',
    'log_try_delete' => 'प्रयास गर्नुहोस् मेटाउनुहोस्: नाम डेटा मा: मोड्युल',
    'log_try_delete_selected' => 'चयन गर्नुहोस् मेट्ने मेमोरी: मोड्युल',
    'log_try_delete_image' => 'को छवि मेटाउने प्रयास गर्नुहोस्: नाम डेटा मा: मोड्युल',
    'log_try_update' => 'अपडेट गर्नुहोस्: डेटा डाटा मा: मोड्युल ',
    'log_add' => 'नयाँ डेटा थप्नुहोस्: नाममा: मोड्युल',
    'log_update' => 'डेटा अपडेट गर्नुहोस्: मा नाम: मोड्युल',
    'log_delete' => 'डेटा मेटाउनुहोस्: मा नाम: मोड्युल',
    'log_delete_image' => 'को छवि मेटाउनुहोस्: मा नाम: मोड्युल',
    'log_login' => ':आईपी ठेगानाको साथ ईमेल लगइन: आईपी',
    'log_forgot' => 'IP को साथ कसैले: आईपी को लागि एउटा पासवर्ड अनुरोध: ईमेल',
    'log_logout' => ':ईमेल लगआउट',

    'alert_delete_selected' => 'तपाइँ निश्चित रूपमा सबै चयन गरिएको डेटा मेटाउन चाहानुहुन्छ ?',
    'alert_delete_selected_success' => 'छानिएका सफलता मेटाउनुहोस्!',
    'alert_bulk_action_button' => 'के तपाई निश्चित हुनुहुन्छ?',
    'alert_action' => 'You have :कार्य सफलतापूर्वक!',
    'alert_add_data_success' => 'डेटा थपिएको छ !',
    'alert_add_data_failed' => 'डाटा सुरक्षित गर्न असफल भयो!',
    'alert_update_data_success' => 'डाटा अपडेट गरिएको छ !',
    'alert_update_data_failed' => 'डेटा अद्यावधिक गर्न असफल भयो',
    'alert_delete_data_success' => 'डेटा सफलता मेटाउनुहोस् !',
    'alert_want_to_logout' => 'तपाई लगआउट गर्न चाहानुहुन्छ ?',
    'alert_warning' => "ओहो",
    'alert_danger' => 'केहि गलत भयो ....',
    'alert_success' => 'वाह, राम्रो काम...',
    'alert_info' => 'जानकारी',
    'alert_primary' => 'जानकारी',
    'alert_session_expired' => 'तपाइँको सत्र समाप्त भयो, कृपया पुन: लग इन गर्नुहोस् !',
    'alert_password_wrong' => 'क्षमा गर्नुहोस् तपाईको पासवर्ड गलत छ!',
    'alert_required' => 'कृपया सबै आवश्यक फिल्डहरू सही रूपमा भर्न निश्चित गर्नुहोस्',
    'alert_error_ajax' => 'ठीक छ, यो शर्मिला छ, केहि गल्ती भयो, हामी चाँडै ठीक गर्नेछौं !',
    'alert_validation_error' => 'कृपया फाराम सही तरिका भर्नुहोस्:: त्रुटि',
    'alert_select_a_data' => 'कृपया कम से कम एक डेटा छान्नुहोस्!',

    'add_data_page_title' => 'थप्नुहोस्: मोड्युल',
    'edit_data_page_title' => 'सम्पादन गर्नुहोस्: मोड्युल',
    'detail_data_page_title' => 'विस्तार: मोड्युल',

    'default_module_description' => 'डेटा सूची',

    'delete_description_confirm' => "तपाईं यस रेकर्ड डेटा पुन: प्राप्ति गर्न सक्षम हुनुहुन्न!",
    'delete_title_confirm' => "साच्चै हो ?",


    'action_show_data' => 'डेटा देखाउनुहोस्',
    'action_add_data' => 'डेटा थप्नुहोस्',
    'action_delete_selected' => 'चयन गरिएको मेट्नुहोस्',

    'action_label' => 'कार्य',
    'action_detail_data' => 'विवरण डेटा',
    'action_edit_data' => 'डाटा सम्पादन गर्नुहोस्',
    'action_delete_data' => 'मेटाउन',


    'button_cancel' => 'रद्द गर्नुहोस्',
    'button_add' => 'डेटा थप्नुहोस्',
    'button_edit' => 'डाटा सम्पादन गर्नुहोस्',
    'button_back' => 'पछाडि',
    'button_save' => 'बचत गर्नुहोस्',
    'button_save_more' => 'बचत गर्नुहोस् र अधिक थप्नुहोस्',
    'button_import' => 'डेटा आयात गर्नुहोस्',
    'button_export' => 'डाटा निर्यात गर्नुहोस्',
    'button_filter' => 'फिल्टर क्रमबद्ध गर्नुहोस्',
    'button_close' => 'बन्द गर्नुहोस्',
    'button_submit' => 'पेश गर्नुहोस्',
    'button_logout' => 'बाहिर निस्कनु',
    'button_sign_in' => 'साइन इन',
    'button_selected_action' => 'थोक क्रियाहरू',
    'button_download_file' => 'डाउनलोड फाइल',
    'button_reset' => 'पुनःसेट गर्नुहोस्',
    'button_add_to_table' => 'तालिकामा थप्नुहोस्',

    'export_dialog_title' => "डाटा निर्यात गर्नुहोस्",
    'export_dialog_filename' => 'फाइल नाम',
    'export_dialog_help_filename' => 'तपाइँका चाहना अनुसार फाइलनाम पुन: नामाकरण गर्न सक्नुहुन्छ',
    'export_dialog_maxdata' => "अधिकतम डाटा",
    'export_dialog_help_maxdata' => 'प्रति निर्यात सत्रमा न्यूनतम 1 र अधिकतम 100,000 पङ्क्तिहरू',
    'export_dialog_columns' => 'स्तम्भहरू',
    'export_dialog_format_export' => 'ढाँचा निर्यात',
    'export_dialog_show_advanced' => 'उन्नत निर्यात देखाउनुहोस्',
    'export_dialog_page_size' => 'पृष्ठ आकार',
    'export_dialog_set_default' => 'पूर्वनिर्धारित पेपर साइजको रूपमा सेट गर्नुहोस्',
    'export_dialog_page_orientation' => 'पृष्ठ अभिविन्यास',

    'import_page_title' => 'डेटा आयात गर्नुहोस्: मोड्युल',
    'dashboard_default_text' => 'ड्यासबोर्डको एप्समा स्वागत छ: एपनाम',
    'form_back_to_list' => 'सूची डेटामा फर्कनुहोस्: मोड्युल',
    'not_logged_in' => 'तपाईं लग इन हुनुहुन्न !',
    'menu_navigation' => "नेभिगेशन",
    'table_data_not_found' => "कुनै डेटा उपलब्ध छैन",
    "notice_delete_file_upload" => "* यदि तपाइँ अन्य फाइल अपलोड गर्न चाहानुहुन्छ, कृपया पहिले फाईल मेटाउनुहोस्।",
    "file_broken" => "ओहो फाइल जस्तै टूटेको जस्तो देखिन्छ! मेट्नुहोस् र पुन: अपलोड क्लिक गर्नुहोस्।",


    'denied_access' => 'क्षमा गर्नुहोस् तपाईंसँग यो क्षेत्रमा पहुँच गर्न विशेषाधिकार छैन!',
    'denied_update' => 'क्षमा गर्नुहोस् तपाईंसँग डेटा अद्यावधिक गर्न विशेषाधिकार छैन !',
    'denied_create' => 'क्षमा गर्नुहोस् तपाईंसँग डेटा सिर्जना गर्न विशेषाधिकार छैन !',
    'denied_delete' => 'क्षमा गर्नुहोस् तपाईंसँग डेटा मेटाउन विशेषाधिकार छैन !',

    'user_image' => 'प्रयोगकर्ता छवि',
    'online' => 'अनलाइन',
    'controller_route_404' => 'नियन्त्रक / मार्ग फेला परेन',
    'home' => 'घर',
    'Notifications' => 'अधिसूचनाहरू',
    'Privileges' => 'विशेषाधिकार',
    'Privileges_Roles' => 'विशेषाधिकार भूमिकाहरू',
    'Add_New_Privilege' => 'नयाँ विशेषाधिकार थप्नुहोस्',
    'List_Privilege' => 'विशेषाधिकार सूची',
    'add_user' => 'प्रयोगकर्ता थप्नुहोस्',
    'List_users' => 'सूची प्रयोगकर्ताहरू',
    'Menu_Management' => 'मेनु व्यवस्थापन',
    'Add_New_Setting' => 'नयाँ सेटिङ थप्नुहोस्',
    'Add_New_Module' => 'नयाँ मोड्युल थप्नुहोस्',
    'List_Module' => 'सूची मोड्युल',
    'Add_New_Statistic' => 'नयाँ तथ्याङ्क थप्नुहोस्',
    'List_Statistic' => 'तथ्याङ्क सूची',
    'Add_New_API' => 'नयाँ API थप्नुहोस्',
    'API_Generator' => 'API जेनरेटर',
    'Statistic_Builder' => 'सांख्यिक बिल्डर',
    'Module_Generator' => 'मोड्युल जेनरेटर',
    'settings' => 'सेटिङ्हरू',
    'Users_Management' => 'उपयोगकर्ता प्रबंधन',
    'list_API' => 'सूची API (प्रलेखन)',
    'Generate_Screet_Key' => 'गुप्त कुञ्जी उत्पन्न गर्नुहोस्',
    'Add_New_Email' => 'नयाँ इमेल थप्नुहोस्',
    'List_Email_Template' => 'ई-मेल टेम्प्लेट सूची',
    'Email_Templates' => 'इमेल टेम्प्लेटहरू',
    'Log_User_Access' => 'लग प्रयोगकर्ता पहुँच',
    'SUPERADMIN' => 'सुपररडिन',

    'click_here' => 'यहाँ क्लिक गर्नुहोस्',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'दायाँ',
    'left' => 'बायाँ',

    'all_rights_reserved' => 'सर्वाधिकार सुरक्षित',
    'copyright' => 'प्रतिलिपि अधिकार',
    'powered_by' => 'Powered by',

    'notification_you_have' => 'तपाईँ सँग छ',
    'notification_notification' => 'अधिसूचनाहरू',
    'notification_new' => 'तपाईंको नयाँ अधिसूचना छ !',

    'login_register_style' => 'लगइन दर्ता शैली',
    'email_setting' => 'इमेल सेटिङ',
    'application_setting' => 'अनुप्रयोग सेटिङ',

    // table filter & sort
    'filter_select_operator_type' => 'अपरेटरको प्रकार छान्नुहोस्',
    'filter_ascending' => 'बड्दैछ ',
    'filter_descending' => 'घट्दैछ',
    'filter_equal_to' => '=(बराबर)',
    'filter_like' => 'जस्तै',
    'filter_not_like' => 'जस्तो छैन',
    'filter_greater_than_or_equal' => '>= (धेरै भन्दा धेरै वा समान)',
    'filter_less_than_or_equal' => '<= (भन्दा कम वा समान)',
    'filter_less_than' => '< (भन्दा कम)',
    'filter_greater_than' => '> (भन्दा ठुलो)',
    'filter_not_equal_to' => '!= (बराबर छैन)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'बिर्सनुहोस्',
    'filter_sort_ascending' => 'आरोही क्रमबद्ध गर्नुहोस्',
    'filter_sort_descending' => 'क्रमबद्ध क्रमबद्ध गर्नुहोस्',
    'filter_eg' => 'e.g',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'खोज्नुहोस्',
    'filter_from' => 'बाट',
    'filter_to' => 'लाई',
    'filter_sorting' => 'क्रमबद्ध',

    // confirmation
    'confirmation_yes' => 'हो!',
    'confirmation_no' => 'होइन',

    //filemanager
    'chose_an_image' => 'चित्र छनौट गर्नुहोस् ',
    'chose_an_file' => 'फाईल छान्नुहोस्',

    //action confirmation
    'confirmation_title' => 'पुष्टिकरण',
    'confirmation_text' => 'के तपाई पक्का यो कार्य गर्न चाहनुहुन्छ??',
    'confirmButtonText' => 'हो',


    // privilege
    'privileges_name' => 'विशेषाधिकार नाम',
    'privileges_super_admin' => 'सुपर व्यवस्थापक',
    'privileges_standart_user' => 'मानक प्रयोगकर्ता',
    'privileges_ID' => 'ID',
    'set_as_superadmin' => 'Superadmin को रूपमा सेट गर्नुहोस्',
    'chose_theme_color_select' => '** ब्याकइन्ड थीम रङ छनौट गर्नुहोस्',
    'chose_theme_color' => ' विषयवस्तु रङ',
    'privileges_configuration' => 'विशेषाधिकार कन्फिगुरेसन',
    'privileges_module_list_no' => 'होइन.',
    'privileges_module_list_mod_names' => 'मोड्युलको नाम',
    'privileges_module_list_view' => 'हेर्नुहोस्',
    'privileges_module_list_create' => 'सिर्जना गर्नुहोस्',
    'privileges_module_list_read' => 'पढ्नुहोस्',
    'privileges_module_list_update' => 'अद्यावधिक गर्नुहोस्',
    'privileges_module_list_delete' => 'मेटाउन',

    //datamodal
    'datamodal_select' => 'Select',
    'datamodal_search_and_enter' => 'खोज्नुहोस् र प्रविष्ट गर्नुहोस् ...',
    'datamodal_enter_to_search' => 'खोजी गर्न प्रविष्ट गर्नुहोस्',
    'datamodal_browse_data' => 'डेटा ब्राउज गर्नुहोस्',
    'datamodal_browse_file' => 'फाइल ब्राउज गर्नुहोस्',


    //child
    'table_detail' => 'तालिका विस्तार',
    'your_file_size_is_too_big' => 'तपाईंको फाइल आकार धेरै ठूलो छ',
    'save_changes' => 'परिवर्तनहरू सुरक्षित गर्नुहोस',
    'please_complete_the_form' => 'फारम भर्नुहोस्!',
    'this_field_is_required' => 'यो फिल्ड आवश्यक छ',
    'text_form' => 'फारम',
    "your_file_extension_is_not_allowed " => "तपाईंको फाइल विस्तार अनुमति छैन!",
];
